### ISSUE TITLE
Problem with intel mpi

### ISSUE THREAD

**Issue by KaiWu0** [Azrael3000/tmpi#11] opened 2021-12-17 01:22 UTC
Thank you for maintaing this project, it helps me a lot.
I tried to modify the source file to enable intel mpi, but failed.
I changed
`mpich=$(mpirun --version |grep -i HYDRA)`
to
`mpich=$(mpirun --version |grep -i -e HYDRA -e Intel)`
and comment out (if not, mpirun will end with error: unrecognized argument pmi-port)
```
if [ -n "${mpich}" ]; then
    pmi_arg="-pmi-port"
fi
```

I am using Quantum ESPRESSO, a fortran code. When I enter in tmux and type in
`run < input_script`
to run the program, it ended with

> [cli_1]: write_line error; fd=10 buf=:cmd=init pmi_version=1 pmi_subversion=1
> :
> system msg for write_line failure : Bad file descriptor
> [cli_1]: Unable to write to PMI_fd
> [cli_1]: write_line error; fd=10 buf=:cmd=get_appnum
> :
> system msg for write_line failure : Bad file descriptor
> Abort(1091087) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
> MPIR_Init_thread(136):
> MPID_Init(709).......:
> MPIR_pmi_init(105)...: PMI_Get_appnum returned -1
> [cli_1]: write_line error; fd=10 buf=:cmd=abort exitcode=1091087
> :
> system msg for write_line failure : Bad file descriptor
> *** error in Message Passing (mp) module ***
> *** error code:  8001
> Attempting to use an MPI routine before initializing MPICH
> [Inferior 1 (process 10868) exited with code 01]

Does anyone know how to resolve this problem?
Thank you very much.

**Comment by Azrael3000** [comment] 2021-12-27 14:59
Hi, thanks for letting me know about the issue with Intel MPI. Unfortunately I do not have access to a machine with that flavour of MPI, so I cannot do any testing myself.

I suppose the first two things can be solved rather easily. I don't want to do that just yet though to make sure that those are the only two changes required to make IntelMPI work. As you still seem to have some issues right now, it would be great if you could test the new `reptyr_dev` branch that I just created. While it will run without `reptyr` please make sure it is installed. This branch does not yet contain the fixes for IntelMPI but you can easily add them.

I think your issue is the `run < input_script`. I suspect that run is some type of bash script that you are using that inside contains some `mpirun ...` command. That won't work with tmpi. You need to replace your `mpirun -np X executable ...` with `tmpi X executable`. Also using `<` is a bad idea, from what I see QE supports `-i` instead of `<` so use this instead.

If that still does not work please either post the commands you are using here or try running any simpler MPI program to see whether the issue is with tmpi or with QE.

**Comment by Azrael3000** [comment] 2021-12-27 15:44
https://github.com/Azrael3000/tmpi/blame/ae369dc3aca8a0059c647918eb70660f625b177c/tmpi#L135 @jczhang07 this `-pmi-port` argument, what is it used for? I tried mpich on my local machine and it does not like it either. Is this just for a specific mpich version?

**Comment by Azrael3000** [comment] 2021-12-27 16:20
I just added the changes you requested to the `reptyr_dev` branch. Please try it out.

**Comment by KaiWu0** [comment] 2021-12-28 01:06
Thank you for your help, @Azrael3000. The `reptyr_dev` branch works well for intel mpi.

**Comment by Azrael3000** [comment] 2021-12-30 14:36
Fantastic, thanks for the feedback. Closing this issue then.

**Closed as completed by Azrael3000** 2021-12-30 14:36 UTC
Labels: bug
